/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package panels;

import javax.swing.JOptionPane;

/**
 *
 * @author andra
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        inpCurrentMatches = new javax.swing.JTextField();
        inpCurrentWr = new javax.swing.JTextField();
        inpTargetWr = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        outTotalMatches = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        outTotalMatchesNeeded = new javax.swing.JTextField();
        outCurrLose = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        outCurrWins = new javax.swing.JTextField();
        outWinsNeeded = new javax.swing.JTextField();
        txtProgress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 221));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        jLabel1.setText("Winrate Calculator");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 153, 221));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Input", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inpCurrentMatches.setBackground(new java.awt.Color(51, 153, 221));
        inpCurrentMatches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpCurrentMatchesActionPerformed(evt);
            }
        });
        jPanel2.add(inpCurrentMatches, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 20));

        inpCurrentWr.setBackground(new java.awt.Color(51, 153, 221));
        jPanel2.add(inpCurrentWr, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 100, 20));

        inpTargetWr.setBackground(new java.awt.Color(51, 153, 221));
        jPanel2.add(inpTargetWr, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 100, 20));

        btnCalculate.setBackground(new java.awt.Color(51, 153, 221));
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        jPanel2.add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Current Matches");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Current Winrate");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Target Winrate");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 380, 110));

        jPanel3.setBackground(new java.awt.Color(51, 153, 221));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Total Matches");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        outTotalMatches.setEditable(false);
        outTotalMatches.setBackground(new java.awt.Color(51, 153, 221));
        jPanel3.add(outTotalMatches, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 85, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Total Matches Needed");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Wins");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Losses");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        outTotalMatchesNeeded.setEditable(false);
        outTotalMatchesNeeded.setBackground(new java.awt.Color(51, 153, 221));
        jPanel3.add(outTotalMatchesNeeded, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 120, -1));

        outCurrLose.setEditable(false);
        outCurrLose.setBackground(new java.awt.Color(51, 153, 221));
        outCurrLose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outCurrLoseActionPerformed(evt);
            }
        });
        jPanel3.add(outCurrLose, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 110, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Current Stats");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Target Winrate");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Wins Needed");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        outCurrWins.setEditable(false);
        outCurrWins.setBackground(new java.awt.Color(51, 153, 221));
        jPanel3.add(outCurrWins, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, -1));

        outWinsNeeded.setEditable(false);
        outWinsNeeded.setBackground(new java.awt.Color(51, 153, 221));
        jPanel3.add(outWinsNeeded, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 85, -1));

        txtProgress.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        jPanel3.add(txtProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 360, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 380, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inpCurrentMatchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpCurrentMatchesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpCurrentMatchesActionPerformed

    private void outCurrLoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outCurrLoseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outCurrLoseActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        if(inpCurrentMatches.getText().isEmpty() || inpCurrentWr.getText().isEmpty() || inpTargetWr.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Fill up");
            return;
        }
        
        int currMatches = Integer.parseInt(inpCurrentMatches.getText());
        double currWr = Double.parseDouble(inpCurrentWr.getText());
        double tarWr = Double.parseDouble(inpTargetWr.getText());
        
        if(currMatches < 0 || currWr < 0.0 || currWr > 100 || tarWr < 0.0 || tarWr > 100.0)
        {
            System.out.print("yo");
        }
        if(tarWr <= currWr)
        {
            JOptionPane.showMessageDialog(null, "Your current winrate is already at or above the target!");
        }
        
        int currentWins = (int) Math.round((currWr / 100.0) * currMatches);
        int currentLosses = currMatches - currentWins;
        int requiredMatches = (int) Math.ceil((currentWins - (tarWr / 100.0 * currMatches)) / ((tarWr / 100.0) - 1));
        int totalMatchesNeeded = currMatches + requiredMatches;
        
        outCurrWins.setText(String.valueOf(currentWins));
        outCurrLose.setText(String.valueOf(currentLosses));
        outTotalMatches.setText(String.valueOf(currMatches));
        
        if(requiredMatches > 0)
        {
            outWinsNeeded.setText(String.valueOf(requiredMatches));
            outTotalMatchesNeeded.setText(String.valueOf(totalMatchesNeeded));
            double progress = (double) currentWins / (currentWins + requiredMatches) * 100;
            txtProgress.setText(String.format("You are currently at %.2f%% progress towards your goal.\n", progress));
        }
        
    }//GEN-LAST:event_btnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JTextField inpCurrentMatches;
    private javax.swing.JTextField inpCurrentWr;
    private javax.swing.JTextField inpTargetWr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField outCurrLose;
    private javax.swing.JTextField outCurrWins;
    private javax.swing.JTextField outTotalMatches;
    private javax.swing.JTextField outTotalMatchesNeeded;
    private javax.swing.JTextField outWinsNeeded;
    private javax.swing.JLabel txtProgress;
    // End of variables declaration//GEN-END:variables
}
